// Generated by tools/syncMap.ts from wac-mono's MAP.md — do not edit by hand.
//
// Regenerate with a wac-mono checkout beside this one:
//
//   deno run --allow-read --allow-write site/tools/syncMap.ts
//
// The committed copy is a fallback, for a checkout with no wac-mono beside it. The Pages build
// does have one and runs this script before building, so what the site serves is current as of
// that deploy. The page still rounds the headline figures: they are a snapshot of another
// repository at one moment, and a number like that should not pretend to four significant
// figures even when it happens to have them.

export type BuiltPackage = {
  name: string;
  what: string;
  lines: number;
  tests: number;
};

/** Package count, lines of wac, tests, command-line programs, browser pages. */
export const TOTALS = {
  packages: 34,
  lines: 76656,
  /** wac-mono's *packages* — the number that belongs beside the package table. */
  tests: 1527,
  programs: 48,
  pages: 4,
  /**
   * The whole repository: the packages (1527), and the compiler, harness and tooling
   * around them (1319).
   *
   * An undercount, because a test generated in a helper or a loop is one declaration and several
   * runs — the suites themselves report more than this.
   */
  testsAll: 2846,
  /** Scripts in the bash differential corpus — `packages/sh/test/corpus.ts`. */
  corpus: 817,
  /** Applets `packages/box` dispatches, which is what `boxNames()` returns and `/bin` lists. */
  applets: 63,
  /** Test files written in wac rather than in the host language. */
  wacTests: 132,
};

/** In dependency order, as MAP.md lists them: nothing imports anything above it. */
export const BUILT: BuiltPackage[] = [
  { name: "bytes", what: "Buf — a growable byte buffer.", lines: 339, tests: 28 },
  { name: "std", what: "Containers and the two sum types every program ends up wanting.", lines: 586, tests: 42 },
  { name: "unicode", what: "UTF-8 as code points, and simple case mapping.", lines: 222, tests: 11 },
  { name: "bignum", what: "Arbitrary-precision integers.", lines: 629, tests: 42 },
  { name: "codec", what: "Base16, base32 and base64, from RFC 4648.", lines: 368, tests: 10 },
  { name: "datetime", what: "The proleptic Gregorian calendar, and RFC 3339 timestamps.", lines: 272, tests: 15 },
  { name: "fmt", what: "Numbers to and from text.", lines: 1199, tests: 27 },
  { name: "gzip", what: "gzip (RFC 1952) and DEFLATE (RFC 1951) written in wac.", lines: 1994, tests: 83 },
  { name: "platform", what: "A capability world for wac applications, so a program can be written entirely in wac — no TypeScript of its own — and still read files, tell…", lines: 3426, tests: 116 },
  { name: "regex", what: "A backtracking regular expression engine, with JavaScript's semantics.", lines: 1515, tests: 21 },
  { name: "stream", what: "Run a wac transform as a ReadableStream/WritableStream pair, so it consumes input as it arrives instead of taking the whole thing at once.", lines: 97, tests: 14 },
  { name: "url", what: "A WHATWG URL parser: parse, serialize, and resolve a reference against a base.", lines: 1219, tests: 27 },
  { name: "wacc", what: "Porting the wac compiler to wac, so it can eventually compile itself.", lines: 6902, tests: 56 },
  { name: "zstd", what: "Zstandard (RFC 8878) in wac.", lines: 3038, tests: 48 },
  { name: "abi", what: "The contract ABI, in wac: how a call's arguments become calldata and how returned bytes become values.", lines: 560, tests: 9 },
  { name: "crypto", what: "SHA-256, SHA-512/384, SHA-3, SHAKE, keccak256, HMAC, HKDF, bcrypt_pbkdf, ChaCha20-Poly1305, AES-CTR, AES-GCM, X25519, Ed25519, NIST P-256 and…", lines: 5790, tests: 150 },
  { name: "fs", what: "A filesystem that belongs to the system rather than to the host.", lines: 2065, tests: 34 },
  { name: "http", what: "HTTP/1.1: parsing requests and responses, and writing both.", lines: 1003, tests: 29 },
  { name: "json", what: "JSON (RFC 8259) parsing and serialization, written in wac.", lines: 955, tests: 51 },
  { name: "rlp", what: "Recursive Length Prefix — the Ethereum execution layer's serialisation, in wac.", lines: 317, tests: 8 },
  { name: "tty", what: "What a terminal does to your keystrokes before a program sees them: echo, erase, kill, word erase, ^C, ^D.", lines: 312, tests: 3 },
  { name: "wactest", what: "Assertions for tests written in wac.", lines: 222, tests: 16 },
  { name: "bls", what: "BLS signature verification on BLS12-381 — the Ethereum parameters and encodings.", lines: 4051, tests: 45 },
  { name: "mpt", what: "Merkle-Patricia proofs, verified — the piece that turns \"a provider told me\" into \"the state root I already verified commits to this\".", lines: 489, tests: 27 },
  { name: "server", what: "An HTTP server written in wac.", lines: 328, tests: 20 },
  { name: "sh", what: "A shell, in wac.", lines: 5709, tests: 25 },
  { name: "ssz", what: "Everything an Altair light client needs is done and checked against Ethereum's vectors.", lines: 802, tests: 26 },
  { name: "tls", what: "TLS 1.3 (RFC 8446) in wac.", lines: 3789, tests: 96 },
  { name: "box", what: "62 applets in one program, chosen by the first argument — 61 tools and help, which prints the list.", lines: 6973, tests: 75 },
  { name: "ens", what: "The name a person types, turned into the node a contract is asked about.", lines: 389, tests: 13 },
  { name: "lightclient", what: "The Altair sync protocol works.", lines: 642, tests: 12 },
  { name: "tor", what: "Tor in wac, both ends: a client and SOCKS5 proxy, a relay, a directory authority, an onion-service client, and a test network with no C tor in it.", lines: 16009, tests: 294 },
  { name: "ethrpc", what: "Asking an Ethereum node a question, so the packages that verify answers have something to verify.", lines: 721, tests: 3 },
  { name: "ssh", what: "An SSH-2 client and server, in wac, and ssh and sshd programs built from them.", lines: 3724, tests: 51 },
];
