// Generated by site/tools/syncMap.ts from MAP.md — do not edit by hand.
//
// Regenerate from the repository root:
//
//   deno run --allow-read --allow-write site/tools/syncMap.ts
//
// The committed copy is what the site serves if the script has not run; the Pages build runs it
// before building, so a deploy is current as of that moment. The page still rounds the headline
// figures: they are a snapshot at one moment, and a number like that should not pretend to four
// significant figures even when it happens to have them. Until 2026-08-12 this header told the
// reader to fetch a sibling checkout — three days after the two repositories became one and the
// map moved into this tree.

export type BuiltPackage = {
  name: string;
  what: string;
  lines: number;
  tests: number;
};

/** Package count, lines of wac, tests, command-line programs, browser pages. */
export const TOTALS = {
  packages: 39,
  lines: 124078,
  /** the *packages* — the number that belongs beside the package table. */
  tests: 2338,
  programs: 75,
  pages: 11,
  /**
   * The whole repository: the packages (2338), and the compiler, harness and tooling
   * around them (1390).
   *
   * An undercount, because a test generated in a helper or a loop is one declaration and several
   * runs — the suites themselves report more than this.
   */
  testsAll: 3728,
  /** Scripts in the bash differential corpus — `packages/sh/test/corpus.ts`. */
  corpus: 883,
  /** Applets `packages/box` dispatches, which is what `boxNames()` returns and `/bin` lists. */
  applets: 65,
  /** Test files written in wac rather than in the host language. */
  wacTests: 236,
};

/** In dependency order, as MAP.md lists them: nothing imports anything above it. */
export const BUILT: BuiltPackage[] = [
  { name: "bytes", what: "Buf — a growable byte buffer.", lines: 339, tests: 34 },
  { name: "std", what: "Containers and the two sum types every program ends up wanting.", lines: 586, tests: 50 },
  { name: "unicode", what: "UTF-8 as code points, simple case mapping, and whether a code point is printable.", lines: 251, tests: 13 },
  { name: "bignum", what: "Arbitrary-precision integers.", lines: 629, tests: 50 },
  { name: "codec", what: "Base16, base32 and base64, from RFC 4648.", lines: 368, tests: 10 },
  { name: "datetime", what: "The proleptic Gregorian calendar, and RFC 3339 timestamps.", lines: 272, tests: 12 },
  { name: "fmt", what: "Numbers to and from text.", lines: 1199, tests: 21 },
  { name: "gzip", what: "gzip (RFC 1952) and DEFLATE (RFC 1951) written in wac.", lines: 2024, tests: 127 },
  { name: "regex", what: "A backtracking regular expression engine, with JavaScript's semantics — and the two POSIX dialects grep reads, translated into them rather than…", lines: 1515, tests: 22 },
  { name: "stream", what: "Run a wac transform as a ReadableStream/WritableStream pair, so it consumes input as it arrives instead of taking the whole thing at once.", lines: 97, tests: 14 },
  { name: "url", what: "A WHATWG URL parser: parse, serialize, and resolve a reference against a base.", lines: 1219, tests: 27 },
  { name: "zstd", what: "Zstandard (RFC 8878) in wac.", lines: 3033, tests: 72 },
  { name: "abi", what: "The contract ABI, in wac: how a call's arguments become calldata and how returned bytes become values.", lines: 560, tests: 9 },
  { name: "json", what: "JSON (RFC 8259) parsing and serialization, written in wac — and JSON5, as a second entry point.", lines: 1321, tests: 58 },
  { name: "platform", what: "A capability world for wac applications, so a program can be written entirely in wac — no TypeScript of its own — and still read files, tell…", lines: 6090, tests: 213 },
  { name: "rlp", what: "Recursive Length Prefix — the Ethereum execution layer's serialisation, in wac.", lines: 317, tests: 10 },
  { name: "crypto", what: "The hashes, AEADs, curves and one KEM the rest of this repo is built on — written in wac, calling nothing.", lines: 5890, tests: 200 },
  { name: "fs", what: "A filesystem that belongs to the system rather than to the host.", lines: 3283, tests: 42 },
  { name: "http", what: "HTTP/1.1: parsing requests and responses, and writing both.", lines: 1327, tests: 40 },
  { name: "raster", what: "A pixel buffer and the three things a desktop draws into one: rectangles, a one-pixel frame, and text in a fixed cell.", lines: 1071, tests: 27 },
  { name: "tty", what: "What a terminal does to your keystrokes before a program sees them: echo, erase, kill, word erase, ^C, ^D.", lines: 477, tests: 6 },
  { name: "bls", what: "BLS signature verification on BLS12-381 — the Ethereum parameters and encodings.", lines: 4052, tests: 45 },
  { name: "mpt", what: "Merkle-Patricia proofs, verified — the piece that turns \"a provider told me\" into \"the state root I already verified commits to this\".", lines: 489, tests: 28 },
  { name: "server", what: "An HTTP server written in wac.", lines: 328, tests: 20 },
  { name: "sh", what: "A shell, in wac, whose definition of correct is GNU bash: a corpus of scripts runs through both and the two must agree on standard output…", lines: 7445, tests: 30 },
  { name: "ssz", what: "SSZ is how Ethereum's consensus layer lays out data.", lines: 802, tests: 26 },
  { name: "tls", what: "TLS 1.3 (RFC 8446) in wac.", lines: 4203, tests: 130 },
  { name: "wacc", what: "Porting the wac compiler to wac, so it can eventually compile itself.", lines: 29524, tests: 211 },
  { name: "wactest", what: "Assertions for tests written in wac.", lines: 650, tests: 17 },
  { name: "box", what: "65 applets in one program, chosen by the first argument — 64 tools and help, which prints the list.", lines: 8456, tests: 130 },
  { name: "ens", what: "The name a person types, turned into the node a contract is asked about.", lines: 389, tests: 24 },
  { name: "git", what: "git in wac: the object database, a working tree, and a client that clones a real repository over its own TLS.", lines: 5760, tests: 61 },
  { name: "lightclient", what: "A light client follows the beacon chain without downloading it.", lines: 642, tests: 12 },
  { name: "quic", what: "QUIC version 1 — RFC 9000 and RFC 9001 — in wac.", lines: 3259, tests: 86 },
  { name: "tor", what: "Tor in wac, both ends: a client and SOCKS5 proxy, a relay, a directory authority, an onion-service client, and a test network with no C tor in it.", lines: 17271, tests: 313 },
  { name: "wacpkg", what: "Where a wac project says its dependencies come from: wac.json5, read and checked.", lines: 335, tests: 12 },
  { name: "webrtc", what: "WebRTC in wac — the data channel half, following design/system/0008.", lines: 3711, tests: 73 },
  { name: "ethrpc", what: "Asking an Ethereum node a question, so the packages that verify answers have something to verify.", lines: 762, tests: 6 },
  { name: "ssh", what: "An SSH-2 client and server, in wac, and ssh and sshd programs built from them.", lines: 4132, tests: 57 },
];
