// Generated by tools/syncDemos.ts. Do not edit — rerun it.
export const DEMO_SIZES: Record<string, string> = {
  "shell.html": "671K",
  "hash.html": "255K",
  "pixels.html": "234K"
};

/** Where each demo's source and build instructions live. */
export const DEMO_SOURCE: Record<string, string> = {
  "shell.html": "https://github.com/voltrevo/wac-mono/blob/master/packages/box/example/README.md#termwac",
  "hash.html": "https://github.com/voltrevo/wac-mono/blob/master/packages/box/example/README.md#hashwac",
  "pixels.html": "https://github.com/voltrevo/wac-mono/blob/master/packages/platform/example/README.md#pixelswac"
};
