import InlineDemo from "./editor/InlineDemo";
import { CodeBlock, fn_, GITHUB, hl, kw, MONO, op, s, SideBySide, Solo, tp } from "./theme";
import Built from "./sections/Built";
import { TOTALS } from "./data/built";
import CaseStudies from "./sections/CaseStudies";


// Enums and generics: the two features the tour did not have and the tagline did not mention.
// Both compile and run in the browser through `InlineDemo`, and both were run through `wacx`
// before being put here — the generic one twice, because `Pair.of(x, y)` in a return position
// has nothing to infer the type argument from and the spec's form is a typed declaration.

const EX_ENUM = `enum Shape {
  Circle(f64 r), Rect(f64 w, f64 h)

  f64 area(const this) {
    return match (this) {
      case Circle(r): 3.14159 * r * r,
      case Rect(w, h): w * h
    };
  }
}

export f64 circle(f64 r) { return Shape.Circle(r).area(); }
export f64 rect(f64 w, f64 h) { return Shape.Rect(w, h).area(); }`;

const EX_GENERIC = `struct Pair<T> {
  T a;
  T b;

  Pair<T> of(T a, T b) { return Pair<T>(a, b); }
  T left(const this) { return this.a; }
}

export i32 leftInt(i32 x, i32 y) {
  Pair<i32> p = Pair.of(x, y);
  return p.left();
}

export string leftStr(string x, string y) {
  Pair<string> p = Pair.of(x, y);
  return p.left();
}`;

// ── Example code ─────────────────────────────────────────────────────────────

const EX_HELLO = `export string hello() {
  return "Hello, world!";
}`;

const EX_MATH = `export i32 gcd(i32 a, i32 b) {
  while (b != 0) {
    i32 t = b;
    b = a % b;
    a = t;
  }
  return a;
}`;

const EX_ERROR = `// What if you write while(b) instead of while(b != 0)?
//
// error: condition must be bool
//   --> main.wac:2:10
//    |
//  2 |   while (b) {
//    |          ^ expected bool, found i32
//    = help: use a comparison: if (b != 0) { ... }`;

const EX_STRUCT = `export struct Point {
  f64 x;
  f64 y;

  Point create(f64 x, f64 y) {
    return Point(x, y);
  }

  f64 distanceSq(const this, Point other) {
    f64 dx = this.x - other.x;
    f64 dy = this.y - other.y;
    return dx * dx + dy * dy;
  }
}`;

const EX_NULLABLE = `struct Node {
  i32 val;
  Node? next;
}

export i32 sum(Node? head) {
  i32 total = 0;
  Node? cur = head;
  while (cur is not null) {
    total += cur!.val;
    cur = cur!.next;
  }
  return total;
}`;

const EX_ARRAYS = `export i32 sumArray(i32[] arr) {
  i32 total = 0;
  for (i32 i = 0; i < arr.len(); i++) {
    total += arr[i];
  }
  return total;
}`;

const EX_IMPORTS_MAIN = `import { gcd, pow } from "./math.wac";

export i32 test() {
  return gcd(48, 18) * pow(2, 3);
  // 6 * 8 = 48
}`;

const EX_IMPORTS_MATH = `export i32 gcd(i32 a, i32 b) {
  while (b != 0) {
    i32 t = b;
    b = a % b;
    a = t;
  }
  return a;
}

export i32 pow(i32 base, i32 exp) {
  i32 result = 1;
  while (exp > 0) {
    if (exp % 2 == 1) {
      result = result * base;
    }
    base = base * base;
    exp = exp / 2;
  }
  return result;
}`;

const EX_BINDGEN = `// Generated by wacBindgen — zero dependencies
const _wasm = Uint8Array.from(
  atob("AGFzbQEAAAA..."),
  (c) => c.charCodeAt(0),
);

const _instance =
  await WebAssembly.instantiate(_wasm);
const _exports =
  _instance.instance.exports;

export function sumArray(
  arr: Int32Array,
): number {
  const _w_arr = _arrayToWasm_i32(arr);
  return (_exports.sumArray as
    CallableFunction)(_w_arr) as number;
}`;

// ── Component ────────────────────────────────────────────────────────────────

export default function Landing() {
  return (
    <div style={s.page}>
      {/* Gradient glow */}
      <div style={{
        position: "fixed", top: 0, left: 0, right: 0, height: 500,
        background: "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(192,132,252,0.12) 0%, transparent 100%)",
        pointerEvents: "none", zIndex: 0,
      }} />

      {/* Hero */}
      <div style={{ textAlign: "center" }}>
        <h1 style={{
          display: "inline-block",
          fontSize: 110,
          fontWeight: 700,
          fontFamily: "ui-monospace, 'Cascadia Code', 'Fira Code', monospace",
          margin: 0,
          background: "linear-gradient(135deg, #d8b4fe 0%, #a855f7 30%, #6366f1 60%, #22d3ee 100%)",
          WebkitBackgroundClip: "text",
          WebkitTextFillColor: "transparent",
          backgroundClip: "text",
          letterSpacing: "-0.03em",
        }}>wac</h1>
      </div>
      <div style={{ ...s.tagline, textAlign: "center" as const }}>
        A C-family language for WebAssembly GC. Structs, methods, subtyping,
        generics, enums with payloads, nullable refs — and WebAssembly's own
        collector owns the heap, so there is no allocator to write.
      </div>

      <div style={{ ...s.buttons, justifyContent: "center", flexWrap: "wrap", marginBottom: 16 }}>
        <a href="#/playground" style={s.btnPrimary}>Playground</a>
        {/* A real shell, in a tab, from packages/sh unchanged. It was two thirds of the way down
            the page and nobody would ever have found it. */}
        <a href="shell.html" style={s.btnDemo}>Shell in your browser →</a>
        <a href={GITHUB} target="_blank" rel="noopener" style={s.btnSecondary}>GitHub</a>
      </div>
      <div style={{ textAlign: "center", fontSize: 13, color: "#6b7280", marginBottom: 40 }}>
        also running here:{" "}
        <a href="hash.html" style={{ color: "#9ca3af" }}>hash &amp; compress</a>,{" "}
        <a href="pixels.html" style={{ color: "#9ca3af" }}>pixels</a> — whole wac applications on a
        worker, <a href="#demos" style={{ color: "#9ca3af" }}>how they work here</a>
      </div>

      {/* What exists, before the tour of how it reads. Numbers from wac-mono's generated map;
          rounded, because this repo's Pages build has no wac-mono beside it to check them. */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
          gap: 1,
          background: "#2e2e3e",
          border: "1px solid #2e2e3e",
          borderRadius: 6,
          overflow: "hidden",
          marginBottom: 56,
        }}
      >
        {[
          ["packages", String(TOTALS.packages)],
          ["lines of wac", `~${Math.round(TOTALS.lines / 1000)}k`],
          ["tests", `~${Math.round(TOTALS.tests / 100) * 100}`],
          ["programs", String(TOTALS.programs)],
          ["compiler", "~6k TS"],
          ["ts in packages", "0"],
        ].map(([label, value]) => (
          <div key={label} style={{ background: "#181825", padding: "12px 14px" }}>
            <div
              style={{
                fontSize: 11,
                color: "#6b7280",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
              }}
            >
              {label}
            </div>
            <div
              style={{
                fontFamily: "monospace",
                fontSize: 20,
                color: "#e2e8f0",
                fontVariantNumeric: "tabular-nums",
              }}
            >
              {value}
            </div>
          </div>
        ))}
      </div>

      {/* Zero deps */}
      <div style={{ ...s.section, backgroundColor: "#181825", border: "1px solid #2e2e3e", borderRadius: 8, padding: "20px 24px" }}>
        <div style={{ fontSize: 17, fontWeight: 600, color: "#e2e8f0", marginBottom: 8 }}>
          Pure TypeScript. Zero dependencies.
        </div>
        <p style={{ ...s.p, marginBottom: 0 }}>
          The entire compiler — lexer, parser, resolver, type checker, WasmGC
          emitter, and binary builder — is pure TypeScript with no native code,
          no LLVM, no binaryen, no wasm toolchain. It runs in the browser (the
          playground compiles everything client-side) and in Deno/Node. The
          compiler, runtime, and bindgen total ~6,000 lines.
        </p>
      </div>

      {/* The page is a dozen screens tall; without this the second half is undiscoverable.
          The showcase page it was merged from had a contents list and this did not. */}
      <nav
        aria-label="Sections"
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: "6px 20px",
          padding: "14px 0",
          borderTop: "1px solid #2e2e3e",
          borderBottom: "1px solid #2e2e3e",
          marginBottom: 44,
          fontSize: 13,
        }}
      >
        {[
          ["#tour", "language tour"],
          ["#bindgen", "typescript bindgen"],
          ["#built", "what is built"],
          ["#capabilities", "capabilities"],
          ["#demos", "run one here"],
          ["#shell", "a shell"],
          ["#tor", "tor"],
        ].map(([href, label], i) => (
          <a key={href} href={href} style={{ color: "#9ca3af", textDecoration: "none" }}>
            <span style={{ color: "#2dd4bf", fontVariantNumeric: "tabular-nums" }}>
              {String(i + 1).padStart(2, "0")}
            </span>{" "}
            {label}
          </a>
        ))}
      </nav>

      {/* Language tour */}
      <div style={s.section} id="tour">
        <h2 style={s.h2}>Language tour</h2>

        <h3 style={s.h3}>Hello world</h3>
        <p style={s.p}>
          Functions have explicit return types. {kw("export")} makes them
          available to the host and other {tp(".wac")} files.
        </p>
        <InlineDemo initialCode={EX_HELLO} />

        <h3 style={s.h3}>Primitives and control flow</h3>
        <p style={s.p}>
          Types: {tp("i32")} {tp("i64")} {tp("f32")} {tp("f64")} {tp("bool")} {tp("string")}.
          Full control flow: {kw("if")}/{kw("else")}, {kw("while")}, {kw("for")}, {kw("do")}-{kw("while")}, {kw("switch")}, ternary.
        </p>
        <InlineDemo initialCode={EX_MATH} />

        <h3 style={s.h3}>Error diagnostics</h3>
        <p style={s.p}>
          No implicit conversions — write {fn_("while (b != 0)")} not {fn_("while (b)")}.
          Try it — the code block above is editable! The compiler tells you
          exactly what went wrong:
        </p>
        <Solo code={EX_ERROR} lang="wac" />

        <h3 style={s.h3}>Structs and methods</h3>
        <p style={s.p}>
          Structs compile to WasmGC struct types. Methods use {kw("this")} (mutable)
          or {kw("const")} {kw("this")} (readonly). Static methods omit {kw("this")}.
        </p>
        <Solo code={EX_STRUCT} lang="wac" />

        <h3 style={s.h3}>Nullable references</h3>
        <p style={s.p}>
          {op("?")} makes a type nullable. {op("!")} unwraps (traps on null).
          Test with {kw("is")} {kw("null")} / {kw("is")} {kw("not")} {kw("null")}.
        </p>
        <Solo code={EX_NULLABLE} lang="wac" />

        <h3 style={s.h3}>Enums carry payloads, and match is exhaustive</h3>
        <p style={s.p}>
          A variant may hold values, and {kw("match")} over one must cover every case — a missing
          arm is a compile error, not a fallthrough. Generic enums give you {tp("Option<T>")} and{" "}
          {tp("Result<T, E>")}, which is where wac-mono's standard library starts.
        </p>
        <InlineDemo initialCode={EX_ENUM} />

        <h3 style={s.h3}>Generics, monomorphised</h3>
        <p style={s.p}>
          A struct may take type parameters. {tp("Pair<i32>")} and {tp("Pair<string>")} are
          separate types the compiler stamps out — no boxing, and nothing erased, so a{" "}
          {tp("Vec<i32>")} holds machine integers.
        </p>
        <InlineDemo initialCode={EX_GENERIC} />

        <h3 style={s.h3}>Arrays</h3>
        <p style={s.p}>
          GC-managed arrays with {fn_(".len()")} and bounds checking.
          Construct with {tp("i32[5]()")} (sized) or {tp("i32[](1,2,3)")} (fixed).
        </p>
        <Solo code={EX_ARRAYS} lang="wac" />

        <h3 style={s.h3}>Multi-file imports</h3>
        <p style={s.p}>
          File-based imports with {kw("import")} / {kw("from")}. Diamond
          imports resolve correctly. Rename with {kw("as")} to avoid collisions.
        </p>
        <SideBySide
          leftLabel="main.wac" rightLabel="math.wac"
          left={EX_IMPORTS_MAIN} right={EX_IMPORTS_MATH}
          leftLang="wac" rightLang="wac"
        />

        <p style={s.p}>
          Also: four cast modes ({op("as")} lossless, {op("as!")} checked, {op("as~")} lossy, {op("as@")} raw),
          struct subtyping via {kw("struct")} {tp("Rect")} : {tp("Shape")},
          and function references ({tp("fn[i32(i32, i32)]")}).
        </p>
      </div>

      {/* Bindgen */}
      <div style={s.section}>
        <h2 style={s.h2} id="bindgen">TypeScript bindgen</h2>
        <p style={s.p}>
          {fn_("wacBindgen")} produces a self-contained {tp(".ts")} file
          with the wasm binary base64-encoded inline and typed wrapper functions.
          Zero runtime dependencies. Primitive arrays automatically marshal between
          JS typed arrays and WasmGC arrays.
        </p>
        <SideBySide
          leftLabel="wac source" rightLabel="generated typescript"
          left={EX_ARRAYS} right={EX_BINDGEN}
          leftLang="wac" rightLang="ts"
        />
      </div>

      <Built />
      <CaseStudies />

      {/* Footer */}
      <div style={{ borderTop: "1px solid #2e2e3e", paddingTop: 24, display: "flex", gap: 24, fontSize: 13, color: "#6b7280" }}>
        <a href="#/playground" style={{ color: "#9ca3af", textDecoration: "none" }}>Playground</a>
        <a href={`${GITHUB}/tree/master/spec`} target="_blank" rel="noopener" style={{ color: "#9ca3af", textDecoration: "none" }}>Language Spec</a>
        <a href={GITHUB} target="_blank" rel="noopener" style={{ color: "#9ca3af", textDecoration: "none" }}>GitHub</a>
        <a href={MONO} target="_blank" rel="noopener" style={{ color: "#9ca3af", textDecoration: "none" }}>wac-mono</a>
        <span style={{ marginLeft: "auto", color: "#4a4a5a" }}>
          Snippets are real source from those repositories, abridged only by removing lines.
        </span>
      </div>
    </div>
  );
}
