// Generated by `deno task gen:core` from core/read.wac. Do not edit.
//
// `core` — the declarations that ship inside the compiler, reached as `import { Read } from core;`.
// `core/README.md` is the argument for anything being in here at all, and the admission test a new
// declaration has to pass. This file is the reference compiler's embedding of it: no JSX frontend,
// so `core/jsx.wac` is not in it — `compiler/README.md` carries that row.

export const CORE = {
  /**
   * What core's declarations are keyed by, everywhere a file path would otherwise appear —
   * diagnostics, the program map, and the `core$Read` mangling. It cannot collide with a real
   * file, because every source path ends in a frontend's extension and this one does not.
   */
  key: "core",

  /**
   * Which frontend parses it. A provider names this rather than the caller inferring it, because a
   * prefixed specifier has no extension to infer from.
   */
  extension: ".wac",

  source: `\
// What a read answered.
//
// The shape exists because the obvious answer, \`u8[]\`, has a hole in it: an empty array means both
// "the input finished" and "the read failed". Filters that treated the second as the first exited 0
// having written half their output, and a gzip stream produced a *valid* archive of half its input
// with a CRC to match. A companion \`inputError()\` to ask afterwards was tried first and left the
// ordinary path looking exactly as correct as it had been, so anyone who forgot to ask got the old
// behaviour back. This cannot be forgotten: \`match\` is exhaustive, and a caller that ignores
// \`Failed\` does not compile.
//
// It is in \`core\` rather than in a package because both ends of a stream have to name it and no
// adapter can join two copies — see the note at the top of compiler/wacCore.ts.

export enum Read {
  /** Bytes, and never zero of them — an empty answer is \`End\`. */
  Data(u8[] bytes),
  /** The input finished. Not a failure. */
  End,
  /** It did not finish, and this is the host's own message. */
  Failed(string why)
}
`,
} as const;
