#!/usr/bin/env -S deno run --allow-read --allow-write
// Regenerate `src/data/built.ts` from wac-mono's generated MAP.md.
//
//   deno run --allow-read --allow-write tools/syncMap.ts [path-to-wac-mono]
//
// The site's landing page claims what has been built in wac — two dozen packages with their
// sizes and test counts. Those numbers belong to the other repo, and typing them into JSX means
// they are wrong by the end of the week. wac-mono generates `MAP.md` from its own tree and its
// suite fails when that file is stale, so it is the closest thing to a source of truth that
// exists for this, and this reads it.
//
// Not run in CI, deliberately: GitHub Pages builds this repo alone and has no wac-mono beside
// it. So the generated file is committed, and the freshness of the numbers is a thing somebody
// refreshes when they notice, not a thing that can break a deploy. Rounded on the page for the
// same reason — see `src/data/built.ts`.

const mono = Deno.args[0] ?? "../wac-mono";
const map = await Deno.readTextFile(`${mono}/MAP.md`);

const totals = map.match(
  /^([\d,]+) packages, ([\d,]+) lines of wac, ([\d,]+) tests,\s*\n([\d,]+) command-line programs and ([\d,]+) browser pages/m,
);
if (totals === null) {
  console.error("MAP.md's totals line did not parse — has its format changed?");
  Deno.exit(1);
}

type Row = { name: string; what: string; lines: number; tests: number };
const rows: Row[] = [];
// `| [`name`](packages/name/) | summary | 1,234 | 56 | deps |`
for (const m of map.matchAll(/^\| \[`([a-z0-9-]+)`\][^|]*\| ([^|]+) \| ([\d,]+) \| (\d+) \|/gm)) {
  rows.push({
    name: m[1],
    what: m[2].trim().replace(/`/g, ""),
    lines: Number(m[3].replace(/,/g, "")),
    tests: Number(m[4]),
  });
}
if (rows.length === 0) {
  console.error("no package rows parsed from MAP.md");
  Deno.exit(1);
}

const num = (s: string) => Number(s.replace(/,/g, ""));
const out = `// Generated by tools/syncMap.ts from wac-mono's MAP.md — do not edit by hand.
//
// Regenerate with a wac-mono checkout beside this one:
//
//   deno run --allow-read --allow-write tools/syncMap.ts ../wac-mono
//
// The numbers are a snapshot rather than a live figure, and the page rounds the headline ones
// for that reason: this repo's Pages build has no wac-mono beside it, so nothing here can be
// checked at deploy time. A number that cannot be checked should not pretend to four
// significant figures.

export type BuiltPackage = {
  name: string;
  what: string;
  lines: number;
  tests: number;
};

/** Package count, lines of wac, tests, command-line programs, browser pages. */
export const TOTALS = {
  packages: ${num(totals[1])},
  lines: ${num(totals[2])},
  tests: ${num(totals[3])},
  programs: ${num(totals[4])},
  pages: ${num(totals[5])},
};

/** In dependency order, as MAP.md lists them: nothing imports anything above it. */
export const BUILT: BuiltPackage[] = [
${rows.map((r) => `  { name: ${JSON.stringify(r.name)}, what: ${JSON.stringify(r.what)}, lines: ${r.lines}, tests: ${r.tests} },`).join("\n")}
];
`;

await Deno.mkdir(new URL("../src/data", import.meta.url).pathname, { recursive: true });
await Deno.writeTextFile(new URL("../src/data/built.ts", import.meta.url).pathname, out);
console.log(`src/data/built.ts: ${rows.length} packages, ${totals[3]} tests`);
