// Compiling what the reader typed, with wacc.
//
// The playground has always compiled snippets with the *reference*, because a page can import
// JavaScript and the reference is TypeScript this site's build transpiles. So the playground refuses
// everything the reference does not have — JSX, components, fragments, an omitted nullable field, the
// bit methods — which is to say the language's own spec examples do not compile in its own
// playground. `issues/lang/0105`.
//
// `site/tools/syncWacc.ts` writes `public/wacc-api.js`: wacc's module with its API bound, in
// JavaScript, generated by wacc's own bindgen. This is the other half — the *shape* conversion.
//
// ## What the runner needs, which is less than it looks
//
// `run.worker.ts` hands a `WacCompiled` to `wacInstance`, and between them they read exactly three
// things: the module's bytes, the exported signatures, and the callback dispatchers. Structs and
// enums are in that type for `wacBindgen`'s benefit, not the runner's — a value of one crosses as an
// opaque reference either way. So this converts three lists and leaves the rest empty, which is why
// it is forty lines rather than a second copy of the compiler's metadata.

import type { WacCallback, WacCompiled, WacExport } from "../../../compiler/wacCompile.ts";
import {
  type Callback,
  parseCallbacks,
  parseSigs,
} from "../../../packages/wacc/tools/waccBindgen.ts";

/** The half of wacc's API this needs, as the generated asset exposes it. */
export type WaccModule = {
  diagnoseFiles(paths: string[], sources: string[], entry: string): string;
  blockedFiles(paths: string[], sources: string[], entry: string): string;
  emitFiles(paths: string[], sources: string[], entry: string): Uint8Array;
  exportSigsFiles(paths: string[], sources: string[], entry: string): string;
  bindTypesFiles(paths: string[], sources: string[], entry: string): string;
};

/** A diagnostic, in the shape the editor's gutter wants. */
export type WaccDiagnostic = { file: string; line: number; col: number; message: string };

export type WaccResult =
  | { ok: true; compiled: WacCompiled }
  | { ok: false; diagnostics: WaccDiagnostic[] };

/**
 * `file\tline\tcol\tphase\tmessage\tnote\thint\twidth` per line, which is what `diagnoseFiles`
 * answers with. The note is where the useful half of a wacc diagnostic lives — *"`Card` needs
 * `count`"* — so it is appended rather than dropped.
 */
export function parseDiagnostics(wire: string): WaccDiagnostic[] {
  const out: WaccDiagnostic[] = [];
  for (const line of wire.split("\n")) {
    if (line === "") continue;
    const [file, l, c, , message, note] = line.split("\t");
    out.push({
      file,
      line: Number(l),
      col: Number(c),
      message: note ? `${message} — ${note}` : message,
    });
  }
  return out;
}

/** wacc's callbacks, named the way the module actually exports and imports them. */
function callbacksOf(cbs: Callback[]): WacCallback[] {
  return cbs.map((c) => ({
    helper: `$bind$fnref_${c.index}`,
    field: `cb${c.index}`,
    type: c.wac,
    params: c.params,
    ret: c.ret,
    // The emitter writes this many trampolines per signature. A host that registers more than that
    // is refused by `wacInstance` with the count, which is the same limit the module was built with.
    slots: 16,
  }));
}

/** wacc's export signatures, with positional names since the wire carries types only. */
function exportsOf(wire: string): WacExport[] {
  return parseSigs(wire).map((s) => ({
    name: s.name,
    ret: s.ret,
    params: s.params.map((type, i) => ({ name: `a${i}`, type })),
  }));
}

/**
 * Compile with wacc and answer in the shape the runner already understands.
 *
 * Both halves of "does it compile" are asked, because a build runs both: what the checker refuses,
 * and what the emitter declines. The second is rarer and reads differently — it names a construct
 * rather than a mistake — so it is reported as a diagnostic against the entry rather than thrown.
 */
export function compileWithWacc(
  wacc: WaccModule,
  files: Record<string, string>,
  entry: string,
): WaccResult {
  const paths = Object.keys(files);
  const sources = paths.map((p) => files[p]);

  const diagnosed = wacc.diagnoseFiles(paths, sources, entry);
  if (diagnosed !== "") return { ok: false, diagnostics: parseDiagnostics(diagnosed) };

  const blocked = wacc.blockedFiles(paths, sources, entry);
  if (blocked !== "") {
    return {
      ok: false,
      diagnostics: [{ file: entry, line: 1, col: 1, message: `wacc cannot emit this yet: ${blocked}` }],
    };
  }

  const wire = wacc.bindTypesFiles(paths, sources, entry);
  return {
    ok: true,
    compiled: {
      wasm: wacc.emitFiles(paths, sources, entry),
      exports: exportsOf(wacc.exportSigsFiles(paths, sources, entry)),
      callbacks: callbacksOf(parseCallbacks(wire)),
      // **Everything below is read by `wacBindgen` and not by the runner**, which was worth checking
      // rather than assuming: `wacInstance` touches `wasm`, `exports` and `callbacks` and nothing
      // else. A struct or an enum crosses as an opaque reference and what is done with it goes
      // through the module's own accessors; an array is converted by the same helpers by name.
      structs: [],
      enums: [],
      arrays: [],
      boxed: [],
      funcrefs: [],
      // The emitter writes trap messages; nothing here reads the flag, and claiming `true` would be
      // a claim about a module this file did not build.
      trapMessages: false,
    },
  };
}
