// Interop with a real browser: Chromium's WebRTC stack, which is libwebrtc.
//
// Everything else in this package is measured against aiortc, coturn and OpenSSL. They are
// independent implementations and they are not the one that matters most: **libwebrtc is what
// WebRTC is**, in the sense that every other implementation was written to talk to it, and its
// description is what a data channel in the wild actually looks like.
//
// ## What this can test here, and what it cannot
//
// **It cannot connect.** Chromium in this container gathers **zero ICE candidates** — gathering
// reaches `complete` and produces none, with `--allow-loopback-in-peer-connection`, with
// `--force-webrtc-ip-handling-policy=default`, and with mDNS masking disabled, on a machine whose
// `eth0` has an ordinary `192.168.80.2`. A peer with no candidate cannot send a connectivity check,
// so ICE, DTLS and a data channel against a browser are **not testable in this environment** — see
// `issues/system/0150`.
//
// What is left is real and worth having: **libwebrtc's own SDP**, generated by an
// `RTCPeerConnection` with a data channel on it, read by `src/sdp.wac`. That is the direction that
// finds omissions, and a browser's description differs from aiortc's — `a=extmap-allow-mixed`,
// `a=msid-semantic`, `a=ice-options:trickle`, and a max-message-size four times larger.
//
// ## Running it
//
// Needs Chromium and playwright at `~/pw`, which `docs/development.md` describes installing. It
// fails rather than skips when absent, for the reason the rest of this package does.

import { wacBind } from "../../../harness/wacBind.ts";

function assertEquals<T>(got: T, want: T, msg?: string): void {
  if (got !== want) {
    throw new Error(
      `assertEquals failed${msg === undefined ? "" : ` — ${msg}`}\n  got:  ${JSON.stringify(got)}\n  want: ${JSON.stringify(want)}`,
    );
  }
}

const ours = await wacBind("packages/webrtc/test/wac/sdp_probe.wac") as unknown as {
  offer(sessionId: bigint, ufrag: string, password: string, fingerprint: string, setup: string,
    candidates: string): string;
  candidateLine(c: string): string;
  attr(sdp: string, name: string): string;
  printOf(sdp: string): string;
  hasChannel(sdp: string): boolean;
  colons(digest: Uint8Array): string;
};

/**
 * Run a script in Chromium and return its stdout.
 *
 * **From `~/pw`, beside playwright's `node_modules`.** `NODE_PATH` does not apply to ESM `import`,
 * only to CommonJS `require`, so a script anywhere else fails with "Cannot find package
 * 'playwright'" however the environment is set — which reads as a missing install rather than as a
 * resolution rule, and cost a cycle here.
 */
async function inBrowser(script: string, ms = 60_000): Promise<string> {
  const file = `${Deno.env.get("HOME")}/pw/.wac-browser-${crypto.randomUUID()}.mjs`;
  await Deno.writeTextFile(file, script);
  const child = new Deno.Command("node", { args: [file], stdout: "piped", stderr: "piped" }).spawn();
  const timer = setTimeout(() => {
    try {
      child.kill("SIGKILL");
    } catch { /* gone */ }
  }, ms);
  try {
    const { code, stdout, stderr } = await child.output();
    if (code !== 0) {
      throw new Error(`the browser run exited ${code}:\n` +
        new TextDecoder().decode(stderr).trim().slice(-900));
    }
    return new TextDecoder().decode(stdout).trim();
  } finally {
    clearTimeout(timer);
    await Deno.remove(file).catch(() => {});
  }
}

Deno.test({
  name: "we read the SDP a browser generates for a data channel",
  sanitizeResources: false,
  sanitizeOps: false,
  fn: async () => {
    const out = await inBrowser(`
import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage();
const sdp = await page.evaluate(async () => {
  const pc = new RTCPeerConnection({ iceServers: [] });
  pc.createDataChannel("chat");
  await pc.setLocalDescription(await pc.createOffer());
  return pc.localDescription.sdp;
});
console.log(JSON.stringify(sdp));
await browser.close();
process.exit(0);
`);
    const sdp = JSON.parse(out) as string;

    assertEquals(ours.hasChannel(sdp), true, `no data channel section in Chromium's offer:\n${sdp}`);
    const ufrag = ours.attr(sdp, "ice-ufrag");
    const pwd = ours.attr(sdp, "ice-pwd");
    assertEquals(ufrag.length > 0, true, "an ice-ufrag");
    assertEquals(pwd.length > 0, true, "and an ice-pwd — what our checks would be signed with");
    assertEquals(ufrag.includes(" "), false, "a value stops at the end of its line");

    const fp = ours.printOf(sdp);
    assertEquals(fp.length, 95,
      `a sha-256 fingerprint is 95 characters of colon-separated hex; we read ${fp.length}: ${fp}`);
    assertEquals(fp.toUpperCase(), fp, "upper case, as libwebrtc writes it");
    assertEquals(ours.attr(sdp, "setup"), "actpass", "an offer leaves the DTLS role open");
    assertEquals(ours.attr(sdp, "sctp-port"), "5000");

    // **libwebrtc's own numbers, which differ from aiortc's**, and are the ones a real peer expects.
    assertEquals(ours.attr(sdp, "max-message-size"), "262144",
      "a browser offers 256 KiB where aiortc offers 64 KiB — worth reading off it rather than " +
        "assuming, since ours has to be a number the other end will accept");
    assertEquals(ours.attr(sdp, "ice-options"), "trickle",
      "and it expects trickle ICE, which this package does not implement");

    // The line-oriented reader must not find an attribute inside another line's value. A browser's
    // description has `a=group:BUNDLE 0` and `a=msid-semantic: WMS` above `a=mid:0`, which is the
    // arrangement that catches a substring search.
    assertEquals(ours.attr(sdp, "mid"), "0");
    assertEquals(ours.attr(sdp, "group"), "BUNDLE 0");
    assertEquals(ours.attr(sdp, "nonesuch"), "", "and an attribute that is not there is empty");
  },
});

Deno.test({
  name: "and the browser gathers no ICE candidates here, which is why it cannot be connected to",
  sanitizeResources: false,
  sanitizeOps: false,
  fn: async () => {
    // **This asserts a limitation, on purpose.** Everything above SDP in this package is measured
    // against aiortc and OpenSSL because a browser in this container cannot complete a connection —
    // and a limitation nothing checks is one that stays in the documentation after it stops being
    // true. When Chromium starts gathering here, this test fails and is the reminder to write the
    // interop test that is currently impossible. `issues/system/0150`.
    const out = await inBrowser(`
import { chromium } from "playwright";
const browser = await chromium.launch({ args: [
  "--no-sandbox",
  "--allow-loopback-in-peer-connection",
  "--force-webrtc-ip-handling-policy=default",
  "--disable-features=WebRtcHideLocalIpsWithMdns",
] });
const page = await browser.newPage();
await page.setContent("<html><body>x</body></html>");
const r = await page.evaluate(async () => {
  const pc = new RTCPeerConnection({ iceServers: [] });
  pc.createDataChannel("x");
  const cands = [];
  pc.addEventListener("icecandidate", (e) => { if (e.candidate) cands.push(e.candidate.candidate); });
  await pc.setLocalDescription(await pc.createOffer());
  await new Promise((r) => setTimeout(r, 4000));
  return { gathering: pc.iceGatheringState, candidates: cands };
});
console.log(JSON.stringify(r));
await browser.close();
process.exit(0);
`);
    const r = JSON.parse(out) as { gathering: string; candidates: string[] };
    assertEquals(r.gathering, "complete", "gathering finishes rather than hanging");
    assertEquals(r.candidates.length, 0,
      `Chromium gathered ${r.candidates.length} candidate(s) — it could not before, so browser ` +
        `interop for ICE, DTLS and a data channel is now possible and 0150 should be closed. ` +
        `Candidates: ${r.candidates.join(" | ")}`);
  },
});
