// SDP, against aiortc's parser and against the SDP a real `RTCPeerConnection` produces.
//
// `design/system/0008` step 6. Two directions, and both matter for different reasons:
//
//   - **aiortc parses our offer** and gets the ICE credentials, the fingerprint and the SCTP
//     capability out of it. An offer a peer cannot parse is where a data channel fails before any
//     packet is sent, and it fails as "invalid SDP" with no hint about which line.
//   - **we parse aiortc's**, which is generated by a full `RTCPeerConnection` with a real data
//     channel on it — so it has the lines a browser sends rather than the lines we thought of.
//
// The second is the one that finds omissions. Our own offer only contains what we knew to write.

import { wacBind } from "../../../harness/wacBind.ts";

function assertEquals<T>(got: T, want: T, msg?: string): void {
  if (got !== want) {
    throw new Error(
      `assertEquals failed${msg === undefined ? "" : ` — ${msg}`}\n  got:  ${JSON.stringify(got)}\n  want: ${JSON.stringify(want)}`,
    );
  }
}

const ours = await wacBind("packages/webrtc/test/wac/sdp_probe.wac") as unknown as {
  offer(sessionId: bigint, ufrag: string, password: string, fingerprint: string, setup: string,
    candidates: string): string;
  candidateLine(c: string): string;
  attr(sdp: string, name: string): string;
  printOf(sdp: string): string;
  hasChannel(sdp: string): boolean;
  colons(digest: Uint8Array): string;
};

async function python(code: string): Promise<string> {
  const p = new Deno.Command("python3", { args: ["-c", code], stdout: "piped", stderr: "piped" });
  const { code: rc, stdout, stderr } = await p.output();
  if (rc !== 0) {
    throw new Error(`python exited ${rc}: ${new TextDecoder().decode(stderr).trim().slice(-500)}`);
  }
  return new TextDecoder().decode(stdout).trim();
}

const FINGERPRINT = "96:E0:AA:F2:B4:46:16:EC:63:75:AB:2E:7F:0E:D5:CD:EF:25:B4:99:91:20:9D:94:D7:AA:93:C0:DC:6B:3B:83";

Deno.test("aiortc parses our offer and gets everything it needs from it", async () => {
  const candidates = ours.candidateLine("wac1 1 udp 2130706431 127.0.0.1 45678 typ host");
  const sdp = ours.offer(1234567890n, "wacUF", "wac-password-0123456789", FINGERPRINT,
    "actpass", candidates);

  const out = await python(`
from aiortc.sdp import SessionDescription
sdp = ${JSON.stringify(sdp)}
d = SessionDescription.parse(sdp)
m = d.media[0]
print(m.kind, m.profile, m.ice.usernameFragment, m.ice.password,
      m.dtls.fingerprints[0].algorithm, m.dtls.fingerprints[0].value,
      m.dtls.role, m.sctpCapabilities.maxMessageSize, m.sctp_port, len(m.ice_candidates))
`);
  const [kind, profile, ufrag, pwd, alg, print, role, maxMsg, sctpPort, candCount] = out.split(" ");
  assertEquals(kind, "application", "a data channel is an application media section");
  assertEquals(profile, "UDP/DTLS/SCTP", "over DTLS, over SCTP — the transport stack in one token");
  assertEquals(ufrag, "wacUF", "the ICE credentials the other end will check our checks against");
  assertEquals(pwd, "wac-password-0123456789");
  assertEquals(alg, "sha-256");
  assertEquals(print, FINGERPRINT,
    "and the fingerprint, which is the whole identity of a WebRTC peer — there is no PKI");
  assertEquals(role, "auto", "actpass, which aiortc reports as auto: either end may start DTLS");
  assertEquals(maxMsg, "65536");
  assertEquals(sctpPort, "5000");
  assertEquals(candCount, "1", "and the candidate line came through as a candidate");
});

Deno.test("and we parse the SDP a real RTCPeerConnection generates", async () => {
  // **Generated by aiortc rather than written here.** A description we composed contains what we
  // knew to include; this one contains what a browser sends, which is how a missing line is found.
  const sdp = await python(`
import asyncio
from aiortc import RTCPeerConnection

async def main():
    pc = RTCPeerConnection()
    pc.createDataChannel("chat")
    offer = await pc.createOffer()
    await pc.setLocalDescription(offer)
    print(pc.localDescription.sdp)
    await pc.close()

asyncio.run(main())
`);

  assertEquals(ours.hasChannel(sdp), true, "aiortc's offer has a data channel section");
  const ufrag = ours.attr(sdp, "ice-ufrag");
  const pwd = ours.attr(sdp, "ice-pwd");
  assertEquals(ufrag.length > 0, true, `no ice-ufrag found in:\n${sdp}`);
  assertEquals(pwd.length > 0, true, "and an ice-pwd");
  assertEquals(ufrag.includes(" "), false, "a value stops at the end of its line");

  const fp = ours.printOf(sdp);
  assertEquals(fp.length, 95,
    `a SHA-256 fingerprint is 32 bytes as colon-separated hex — 95 characters — and we read ` +
      `${fp.length}: ${JSON.stringify(fp)}`);
  assertEquals(fp.includes(":"), true, "colon separated");
  assertEquals(fp.toUpperCase(), fp, "and upper case, as every implementation writes it");
  assertEquals(ours.attr(sdp, "setup"), "actpass", "an offer leaves the DTLS role open");
  assertEquals(ours.attr(sdp, "sctp-port"), "5000");

  // The line-oriented reader must not find an attribute inside another line's value — `a=mid:0`
  // occurring after `a=group:BUNDLE 0` is the case that catches a substring search.
  assertEquals(ours.attr(sdp, "mid"), "0");
  assertEquals(ours.attr(sdp, "nonesuch"), "", "and an attribute that is not there is empty");
});

Deno.test("a fingerprint is written the way an SDP wants it", () => {
  // Colon-separated upper-case hex, which is the one place this package formats a value for a human
  // rather than for a parser — and getting it wrong produces an SDP rejected as malformed.
  const digest = Uint8Array.from([0x96, 0xE0, 0xAA, 0xF2, 0x00, 0x0F]);
  assertEquals(ours.colons(digest), "96:E0:AA:F2:00:0F");
  assertEquals(ours.colons(new Uint8Array(0)), "", "nothing to separate");
  assertEquals(ours.colons(Uint8Array.from([0])), "00", "one byte has no separator");
});

Deno.test("bare LF is read as well as CRLF, which is what arrives in practice", () => {
  const sdp = ours.offer(1n, "uf", "pw", FINGERPRINT, "active", "");
  assertEquals(sdp.includes("\r\n"), true, "we write CRLF, as the specification says");
  // A signalling server that normalised the line endings, or a hand-written fixture, gives LF —
  // and refusing that would be strict about the wrong thing.
  const lf = sdp.replaceAll("\r\n", "\n");
  assertEquals(ours.attr(lf, "ice-ufrag"), "uf");
  assertEquals(ours.attr(lf, "setup"), "active");
  assertEquals(ours.printOf(lf), FINGERPRINT);
  assertEquals(ours.hasChannel(lf), true);
});
