// Extracts the spec's multi-file programs by *running* the spec suite, not by reading it.
//
// `wacSpec.test.ts` states 56 of its cases as a `Map` of file name to source — the ones about
// imports, export visibility and cross-file type identity, which are exactly the rules a single-file
// corpus cannot state. Three attempts to lift them out by reading the text disagreed with each other
// (11, 6 and 9 cases), because the file is 9,000 lines of TypeScript carrying wac programs inside
// template literals: a `{` in a program is not a brace to the language around it, and a wac
// `import { x } from "./b.wac"` is indistinguishable from the TypeScript one above it. A fourth
// attempt rewrote 44 of the spec's own programs while trying to relocate the module's imports.
//
// So nothing here parses anything. The suite is copied, its single `wacCompile` import is pointed at
// a shim that records what it is handed, and the copy is run. What comes out is what the spec
// executed — and the copy passing 529/529 exactly as the original does is the check that it is still
// the same suite.
//
//     deno run -A packages/wacc/tools/specMultiCases.ts
//
// Writes `packages/wacc/test/specMultiCases.json`. `specMulti.test.ts` fails when the recorded
// source hash no longer matches `wacSpec.test.ts`, which is what says to run this again.

const REPO = new URL("../../../", import.meta.url).pathname.replace(/\/$/, "");
const SPEC = `${REPO}/compiler/wacSpec.test.ts`;
const OUT = `${REPO}/packages/wacc/test/specCases.json`;

const src = await Deno.readTextFile(SPEC);
const hash = [...new Uint8Array(
  await crypto.subtle.digest("SHA-256", new TextEncoder().encode(src)),
)].map(b => b.toString(16).padStart(2, "0")).join("");

const tmp = await Deno.makeTempDir({ prefix: "wac-specmulti-" });
const shimPath = `${tmp}/shim.ts`;
const casesPath = `${tmp}/cases.json`;

await Deno.writeTextFile(shimPath, shim(casesPath));

// **Only the header, never the tests.** The module's own imports all stand above the first
// `Deno.test(`, and every relative specifier below that line belongs to a program the spec is
// making a claim about. Rewriting those is how the fourth attempt broke 44 cases while reporting
// success, so the split is the safety rule rather than an optimisation.
const split = src.indexOf("Deno.test(");
if (split < 0) throw new Error("no tests found in wacSpec.test.ts");

let redirected = 0;
const header = src.slice(0, split).replace(
  /(\sfrom\s+")(\.[^"]*)(")/g,
  (_m, pre: string, spec: string, post: string) => {
    if (spec === "./wacCompile.ts") { redirected++; return `${pre}${shimPath}${post}`; }
    const abs = spec.startsWith("../") ? `${REPO}/${spec.slice(3)}` : `${REPO}/compiler/${spec.slice(2)}`;
    return `${pre}${abs}${post}`;
  },
);
if (redirected !== 1) throw new Error(`expected one wacCompile import, found ${redirected}`);

// Five tests walk `spec/`, `issues/` and `grammar.md` relative to the module's own URL. The copy has
// moved, so they are told where the original stood — otherwise they walk an empty directory and
// report a resolved walk over nothing.
const copy = (header + src.slice(split)).replaceAll("import.meta.url", `"file://${SPEC}"`);
const copyPath = `${tmp}/spec.copy.test.ts`;
await Deno.writeTextFile(copyPath, copy);

const run = await new Deno.Command(Deno.execPath(), {
  args: ["test", "-A", "--no-check", "--config", `${REPO}/deno.json`, copyPath],
  cwd: REPO,
  stdout: "piped",
  stderr: "piped",
}).output();

const out = new TextDecoder().decode(run.stdout) + new TextDecoder().decode(run.stderr);
const tally = out.match(/(\d+) passed \| (\d+) failed/);
if (!tally) throw new Error(`could not read the suite's tally:\n${out.slice(-2000)}`);
const [, passed, failed] = tally;

// The copy must behave exactly as the original — a recording taken from a suite that ran differently
// is a recording of something else.
if (failed !== "0") {
  throw new Error(`the instrumented copy failed ${failed} tests; it must match the original\n${out.slice(-3000)}`);
}

type Case = { test: string; entry: string; files: [string, string][]; ok: boolean; message: string };
const cases: Case[] = JSON.parse(await Deno.readTextFile(casesPath));

await Deno.writeTextFile(
  OUT,
  JSON.stringify({ source: "compiler/wacSpec.test.ts", sha256: hash, cases }, null, 2) + "\n",
);
await Deno.remove(tmp, { recursive: true });

const rej = cases.filter(c => !c.ok).length;
const multi = cases.filter(c => c.files.length > 1).length;
console.log(`${passed} passed, ${failed} failed; ${cases.length} cases (${rej} illegal, ${cases.length - rej} legal; ${multi} span more than one file) -> ${OUT}`);

function shim(casesOut: string): string {
  return `// Generated by packages/wacc/tools/specMultiCases.ts — records what the suite compiles.
import { wacCompile as real } from "${REPO}/compiler/wacCompile.ts";

const cases: unknown[] = [];
let current = "(none)";

const origTest = Deno.test.bind(Deno);
// deno-lint-ignore no-explicit-any
(Deno as any).test = (a: any, b?: any) => {
  const wrap = (name: string, fn: (t?: unknown) => unknown) => (t?: unknown) => {
    const prev = current;
    current = name;
    try {
      const r = fn(t);
      if (r instanceof Promise) return r.finally(() => { current = prev; });
      current = prev;
      return r;
    } catch (e) { current = prev; throw e; }
  };
  if (typeof a === "string") return origTest(a, wrap(a, b));
  if (typeof a === "function") return origTest(a.name, wrap(a.name, a));
  return origTest({ ...a, fn: wrap(a.name, a.fn) });
};

// deno-lint-ignore no-explicit-any
export function wacCompile(files: any, entry?: any, ...rest: any[]): any {
  // deno-lint-ignore no-explicit-any
  const r = (real as any)(files, entry, ...rest);
  if (files instanceof Map) {
    cases.push({
      test: current,
      entry: typeof entry === "string" ? entry : "main.wac",
      files: [...files.entries()],
      ok: !!r?.ok,
      message: r?.ok ? "" : String(r?.diagnostics?.[0]?.message ?? ""),
    });
  }
  return r;
}

globalThis.addEventListener("unload", () => {
  Deno.writeTextFileSync(${JSON.stringify(casesOut)}, JSON.stringify(cases, null, 2));
});
`;
}
