// wacc's bindgen: TypeScript that calls a wacc-compiled module.
//
// The reference's `wacBindgen.ts` is 1,011 lines and covers every type wac has. This covers the
// types a host most often crosses with — the numbers, `bool`, `string` and a numeric array — and
// says so: `unsupported()` lists what it declined rather than emitting glue that will not work.
//
// The split is deliberate. Which functions are exported and what they take is a question only the
// compiler can answer, so wacc answers it (`exportSigsFiles`); turning that into text is text, and
// lives here, where `waccx` already is.
//
// The module's own helpers do the crossing: `$bind$str_*` and `$bind$arr_*` for the references,
// `$bind$mem`/`$bind$mem_ensure` for the staging buffer. This file writes the calls; it invents
// nothing about the representation.

/** One exported function, as the compiler describes it. */
export type ExportSig = { name: string; ret: string; params: string[] };

/** Parse `name\tret\tparam,param` lines — the shape `exportSigsFiles` returns. */
export function parseSigs(wire: string): ExportSig[] {
  const out: ExportSig[] = [];
  for (const line of wire.split("\n")) {
    if (line === "") continue;
    const [name, ret, params] = line.split("\t");
    out.push({ name, ret, params: params === "" || params === undefined ? [] : params.split(",") });
  }
  return out;
}

const SCALARS = new Set(["i32", "u32", "i64", "u64", "f32", "f64", "bool", "void"]);
/** The arrays that cross through the staging buffer, which is where `_to_mem`/`_from_mem` exist. */
const BULK = new Set(["u8[]", "i8[]", "i32[]", "u32[]", "i64[]", "u64[]", "f32[]", "f64[]"]);

/** Whether this signature is one this generator can write glue for. */
export function supported(sig: ExportSig): boolean {
  const ok = (t: string) => SCALARS.has(t) || t === "string" || BULK.has(t);
  return ok(sig.ret) && sig.params.every(ok);
}

/** The TypeScript type a wac type crosses as. */
function tsType(t: string): string {
  if (t === "void") return "void";
  if (t === "bool") return "boolean";
  if (t === "i64" || t === "u64") return "bigint";
  if (t === "string") return "string";
  if (BULK.has(t)) return arrayClass(t);
  return "number";
}

function arrayClass(t: string): string {
  const el = t.slice(0, -2);
  return {
    "u8": "Uint8Array", "i8": "Int8Array", "i32": "Int32Array", "u32": "Uint32Array",
    "i64": "BigInt64Array", "u64": "BigUint64Array", "f32": "Float32Array", "f64": "Float64Array",
  }[el] ?? "Uint8Array";
}

/** How many bytes one element takes in the staging buffer. */
function width(t: string): number {
  const el = t.slice(0, -2);
  return { "u8": 1, "i8": 1, "i32": 4, "u32": 4, "i64": 8, "u64": 8, "f32": 4, "f64": 8 }[el] ?? 1;
}

/**
 * The generated module: one exported function per wac export, plus the conversions they need.
 *
 * `bytes` is the wasm as a base64 string so the result is a single self-contained file — the same
 * choice the reference makes, and for the same reason: a `.gen.ts` that needs a `.wasm` beside it is
 * two things to keep in step.
 */
export function generate(wasm: Uint8Array, sigs: ExportSig[]): string {
  const usable = sigs.filter(supported);
  const needsMem = usable.some(s => [s.ret, ...s.params].some(t => t === "string" || BULK.has(t)));
  const lines: string[] = [];

  lines.push("// Generated by packages/wacc/tools/waccBindgen.ts — do not edit.");
  lines.push("");
  lines.push(`const WASM = "${btoa(String.fromCharCode(...wasm))}";`);
  lines.push("const bytes = Uint8Array.from(atob(WASM), c => c.charCodeAt(0));");
  lines.push("const $mod = new WebAssembly.Module(bytes as BufferSource);");
  lines.push("const $inst = new WebAssembly.Instance($mod, {});");
  lines.push("const $exports = $inst.exports as Record<string, CallableFunction>;");
  lines.push("");

  if (needsMem) {
    lines.push("const $memory = $inst.exports.$bind$mem as WebAssembly.Memory;");
    lines.push("/** Grow the staging buffer to hold `n` bytes and answer a fresh view of it. */");
    lines.push("function $buffer(n: number): Uint8Array {");
    lines.push("  ($exports.$bind$mem_ensure as CallableFunction)(n);");
    lines.push("  return new Uint8Array($memory.buffer);");
    lines.push("}");
    lines.push("");
    lines.push("function $strTo(s: string): unknown {");
    lines.push("  const b = new TextEncoder().encode(s);");
    lines.push("  $buffer(b.length).set(b, 0);");
    lines.push("  return ($exports.$bind$str_from_mem as CallableFunction)(b.length);");
    lines.push("}");
    lines.push("");
    lines.push("function $strFrom(w: unknown): string {");
    lines.push("  const n = ($exports.$bind$str_to_mem as CallableFunction)(w) as number;");
    lines.push("  return new TextDecoder().decode(new Uint8Array($memory.buffer).slice(0, n));");
    lines.push("}");
    lines.push("");
  }

  for (const t of new Set(usable.flatMap(s => [s.ret, ...s.params]).filter(t => BULK.has(t)))) {
    const el = t.slice(0, -2);
    const cls = arrayClass(t);
    const w = width(t);
    lines.push(`function $arrTo_${el}(a: ${cls}): unknown {`);
    lines.push(`  const view = $buffer(a.length * ${w});`);
    lines.push(`  new ${cls}(view.buffer, 0, a.length).set(a);`);
    lines.push(`  return ($exports.$bind$arr_${el}_from_mem as CallableFunction)(a.length);`);
    lines.push("}");
    lines.push("");
    lines.push(`function $arrFrom_${el}(w: unknown): ${cls} {`);
    lines.push(`  const n = ($exports.$bind$arr_${el}_to_mem as CallableFunction)(w) as number;`);
    lines.push(`  return new ${cls}($memory.buffer.slice(0, n * ${w}));`);
    lines.push("}");
    lines.push("");
  }

  for (const sig of usable) {
    const args = sig.params.map((t, i) => `a${i}: ${tsType(t)}`).join(", ");
    const conv = sig.params.map((t, i) =>
      t === "string" ? `$strTo(a${i})` : BULK.has(t) ? `$arrTo_${t.slice(0, -2)}(a${i})` : `a${i}`
    ).join(", ");
    lines.push(`export function ${sig.name}(${args}): ${tsType(sig.ret)} {`);
    const call = `($exports.${sig.name} as CallableFunction)(${conv})`;
    if (sig.ret === "void") lines.push(`  ${call};`);
    else if (sig.ret === "string") lines.push(`  return $strFrom(${call});`);
    else if (BULK.has(sig.ret)) lines.push(`  return $arrFrom_${sig.ret.slice(0, -2)}(${call});`);
    else if (sig.ret === "bool") lines.push(`  return ${call} !== 0;`);
    else lines.push(`  return ${call} as ${tsType(sig.ret)};`);
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

/** What this generator declined, so a caller learns it rather than discovering it at run time. */
export function unsupported(sigs: ExportSig[]): string[] {
  return sigs.filter(s => !supported(s))
    .map(s => `${s.name}(${s.params.join(", ")}) -> ${s.ret}`);
}
