// `core`, from one source tree into the two compilers that embed it — `design/lang/0009` D3 step 2.
//
//     deno task gen:core           # write both embeddings
//     deno task gen:core --check   # fail if either is out of step
//
// ## Why a generator rather than a shared file
//
// **Neither compiler can read `core` at runtime.** The reference is bundled into the playground and
// has to reach a browser with no filesystem; wacc's copy lives inside a wasm module. So both keep a
// literal, and de-duplicating means generating both from one tree rather than teaching either to
// open a file.
//
// **The two embeddings are not the same text, and should not be.** The reference has no JSX
// frontend, so it gets `Read` alone; wacc gets `Read`, `Attr` and `Node`. That is a documented
// omission — `compiler/README.md` carries the row — and a generator writing one text into both
// would delete it.
//
// ## How the omission is expressed
//
// **By which file a declaration is in.** `core/read.wac` goes to both; `core/jsx.wac` goes to wacc
// only, and the two lists are the constants below. The alternative was a marker inside one shared
// file — `// @wacc-only` or similar — which is a third thing to invent, to parse, and to keep true,
// for a distinction the directory already draws. D3 makes `core` an embedded source *tree*
// regardless, so this is on that path rather than beside it.
//
// ## One thing this changes on purpose
//
// wacc's copy was written without the comments — 239 characters against the reference's 1077 — as a
// hand-maintenance economy. Generating both from one tree gives them back. That is about 800 bytes
// in a 777 KB seed and nothing else: comments do not survive the lexer, so the emitted module is
// unchanged, and the first `deno task seed` after this moves the seed's bytes once and then settles.

const READ = "core/read.wac";
const JSX = "core/jsx.wac";

/** What the reference compiler embeds: no JSX frontend, so no `Node`. */
const REFERENCE = [READ];
/** What wacc embeds. */
const WACC = [READ, JSX];

const REF_OUT = "compiler/wacCore.ts";
const WACC_OUT = "packages/wacc/src/coretext.wac";

const read = async (paths: string[]): Promise<string> => {
  const parts: string[] = [];
  for (const p of paths) parts.push((await Deno.readTextFile(p)).replace(/\n+$/, "\n"));
  return parts.join("\n");
};

/** The text as a TypeScript template literal body. */
function asTemplate(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * The text as a wac expression: one quoted line per source line, concatenated.
 *
 * A line each rather than one long literal, because that is what makes a diff of this generated
 * file readable — a one-line change to `core` should be a one-line change here.
 */
function asWac(text: string): string {
  const lines = text.split("\n");
  if (lines[lines.length - 1] === "") lines.pop();
  const quoted = lines.map((l) =>
    `"${l.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}\\n"`
  );
  return quoted.map((q, i) => (i === 0 ? `  return ${q}` : `         + ${q}`)).join("\n") + ";";
}

const BANNER = (from: string[]) =>
  `Generated by \`deno task gen:core\` from ${from.join(", ")}. Do not edit.`;

async function referenceFile(): Promise<string> {
  return `// ${BANNER(REFERENCE)}
//
// \`core\` — the declarations that ship inside the compiler, reached as \`import { Read } from core;\`.
// \`core/README.md\` is the argument for anything being in here at all, and the admission test a new
// declaration has to pass. This file is the reference compiler's embedding of it: no JSX frontend,
// so \`core/jsx.wac\` is not in it — \`compiler/README.md\` carries that row.

export const CORE = {
  /**
   * What core's declarations are keyed by, everywhere a file path would otherwise appear —
   * diagnostics, the program map, and the \`core$Read\` mangling. It cannot collide with a real
   * file, because every source path ends in a frontend's extension and this one does not.
   */
  key: "core",

  /**
   * Which frontend parses it. A provider names this rather than the caller inferring it, because a
   * prefixed specifier has no extension to infer from.
   */
  extension: ".wac",

  source: \`\\
${asTemplate(await read(REFERENCE))}\`,
} as const;
`;
}

async function waccFile(): Promise<string> {
  return `// ${BANNER(WACC)}
//
// wacc's embedding of \`core\`. \`core/README.md\` says why anything is in there; this file is only the
// text, kept apart from \`emit.wac\` so that a generator owns a whole file rather than splicing into
// one that is also in the seed.

export string coreSource() {
${asWac(await read(WACC))}
}
`;
}

const check = Deno.args.includes("--check");
const wanted: [string, string][] = [
  [REF_OUT, await referenceFile()],
  [WACC_OUT, await waccFile()],
];

const stale: string[] = [];
for (const [path, text] of wanted) {
  const now = await Deno.readTextFile(path).catch(() => null);
  if (now === text) continue;
  if (check) {
    stale.push(now === null ? `${path} is missing` : `${path} is out of step with core/`);
    continue;
  }
  await Deno.writeTextFile(path, text);
  console.log(`wrote ${path} (${text.length} bytes)`);
}

if (check) {
  if (stale.length > 0) {
    console.error(
      `${stale.length} generated file(s) do not match \`core/\`:\n  ${stale.join("\n  ")}\n\n` +
        "Run `deno task gen:core`. Editing the embeddings by hand is what this replaces — the two " +
        "differ by design and the difference is which files each one is built from.",
    );
    Deno.exit(1);
  }
  console.log(`core/: both embeddings are in step`);
} else if (wanted.every(([p]) => p)) {
  console.log("core/: both embeddings written");
}
