// Generated by tools/syncMap.ts from wac-mono's MAP.md — do not edit by hand.
//
// Regenerate with a wac-mono checkout beside this one:
//
//   deno run --allow-read --allow-write tools/syncMap.ts ../wac-mono
//
// The committed copy is a fallback, for a checkout with no wac-mono beside it. The Pages build
// does have one and runs this script before building, so what the site serves is current as of
// that deploy. The page still rounds the headline figures: they are a snapshot of another
// repository at one moment, and a number like that should not pretend to four significant
// figures even when it happens to have them.

export type BuiltPackage = {
  name: string;
  what: string;
  lines: number;
  tests: number;
};

/** Package count, lines of wac, tests, command-line programs, browser pages. */
export const TOTALS = {
  packages: 32,
  lines: 64587,
  /** wac-mono's *packages* — the number that belongs beside the package table. */
  tests: 1307,
  programs: 38,
  pages: 4,
  /**
   * Both suites: wac-mono's packages (1307), its harness and tools (88),
   * and this repo's compiler (1213).
   *
   * An undercount, because a test generated in a helper or a loop is one declaration and several
   * runs — the suites themselves report more than this.
   */
  testsAll: 2608,
};

/** In dependency order, as MAP.md lists them: nothing imports anything above it. */
export const BUILT: BuiltPackage[] = [
  { name: "bytes", what: "Buf — a growable byte buffer.", lines: 256, tests: 25 },
  { name: "regex", what: "A backtracking regular expression engine, with JavaScript's semantics.", lines: 971, tests: 16 },
  { name: "std", what: "Containers and the two sum types every program ends up wanting.", lines: 586, tests: 42 },
  { name: "unicode", what: "UTF-8 as code points, and simple case mapping.", lines: 216, tests: 11 },
  { name: "bignum", what: "Arbitrary-precision integers.", lines: 629, tests: 42 },
  { name: "codec", what: "Base16, base32 and base64, from RFC 4648.", lines: 349, tests: 10 },
  { name: "datetime", what: "The proleptic Gregorian calendar, and RFC 3339 timestamps.", lines: 272, tests: 14 },
  { name: "fmt", what: "Numbers to and from text.", lines: 1199, tests: 27 },
  { name: "gzip", what: "gzip (RFC 1952) and DEFLATE (RFC 1951) written in wac.", lines: 1985, tests: 83 },
  { name: "http", what: "HTTP/1.1: parsing requests and responses, and writing both.", lines: 913, tests: 29 },
  { name: "platform", what: "A capability world for wac applications, so a program can be written entirely in wac — no TypeScript of its own — and still read files, tell…", lines: 3309, tests: 108 },
  { name: "stream", what: "Run a wac transform as a ReadableStream/WritableStream pair, so it consumes input as it arrives instead of taking the whole thing at once.", lines: 97, tests: 14 },
  { name: "url", what: "A WHATWG URL parser: parse, serialize, and resolve a reference against a base.", lines: 1219, tests: 27 },
  { name: "wacc", what: "Porting the wac compiler to wac, so it can eventually compile itself.", lines: 3807, tests: 14 },
  { name: "zstd", what: "Zstandard (RFC 8878) in wac.", lines: 2686, tests: 42 },
  { name: "abi", what: "The contract ABI, in wac: how a call's arguments become calldata and how returned bytes become values.", lines: 560, tests: 6 },
  { name: "crypto", what: "SHA-256, SHA-512/384, SHA-3, SHAKE, keccak256, HMAC, HKDF, bcrypt_pbkdf, ChaCha20-Poly1305, AES-CTR, AES-GCM, X25519, Ed25519, NIST P-256 and…", lines: 5565, tests: 146 },
  { name: "fs", what: "A filesystem that belongs to the system rather than to the host.", lines: 594, tests: 12 },
  { name: "json", what: "JSON (RFC 8259) parsing and serialization, written in wac.", lines: 955, tests: 51 },
  { name: "rlp", what: "Recursive Length Prefix — the Ethereum execution layer's serialisation, in wac.", lines: 317, tests: 8 },
  { name: "wactest", what: "Assertions for tests written in wac.", lines: 222, tests: 16 },
  { name: "bls", what: "BLS signature verification on BLS12-381 — the Ethereum parameters and encodings.", lines: 4049, tests: 45 },
  { name: "ens", what: "The name a person types, turned into the node a contract is asked about.", lines: 251, tests: 8 },
  { name: "mpt", what: "Merkle-Patricia proofs, verified — the piece that turns \"a provider told me\" into \"the state root I already verified commits to this\".", lines: 489, tests: 22 },
  { name: "server", what: "An HTTP server written in wac.", lines: 333, tests: 20 },
  { name: "sh", what: "A shell, in wac.", lines: 6564, tests: 31 },
  { name: "ssz", what: "Everything an Altair light client needs is done and checked against Ethereum's vectors.", lines: 808, tests: 26 },
  { name: "tls", what: "TLS 1.3 (RFC 8446) in wac.", lines: 3685, tests: 75 },
  { name: "box", what: "60 applets in one program, chosen by the first argument.", lines: 4008, tests: 33 },
  { name: "lightclient", what: "The Altair sync protocol works.", lines: 642, tests: 12 },
  { name: "ssh", what: "An SSH-2 client and server, in wac, and ssh and sshd programs built from them.", lines: 3551, tests: 46 },
  { name: "tor", what: "Tor in wac — a client, a relay, a directory authority and an onion-service client, on top of this repo's TLS 1.3 stack.", lines: 13500, tests: 246 },
];
