// Generated by tools/syncMap.ts from wac-mono's MAP.md — do not edit by hand.
//
// Regenerate with a wac-mono checkout beside this one:
//
//   deno run --allow-read --allow-write tools/syncMap.ts ../wac-mono
//
// The numbers are a snapshot rather than a live figure, and the page rounds the headline ones
// for that reason: this repo's Pages build has no wac-mono beside it, so nothing here can be
// checked at deploy time. A number that cannot be checked should not pretend to four
// significant figures.

export type BuiltPackage = {
  name: string;
  what: string;
  lines: number;
  tests: number;
};

/** Package count, lines of wac, tests, command-line programs, browser pages. */
export const TOTALS = {
  packages: 24,
  lines: 40968,
  tests: 899,
  programs: 20,
  pages: 4,
};

/** In dependency order, as MAP.md lists them: nothing imports anything above it. */
export const BUILT: BuiltPackage[] = [
  { name: "bytes", what: "Buf — a growable byte buffer.", lines: 231, tests: 24 },
  { name: "platform", what: "A capability world for wac applications, so a program can be written **entirely in wac** — no TypeScript of its own — and still read files, tell…", lines: 1737, tests: 44 },
  { name: "regex", what: "A backtracking regular expression engine, with JavaScript's semantics.", lines: 924, tests: 15 },
  { name: "std", what: "Containers and the two sum types every program ends up wanting.", lines: 570, tests: 36 },
  { name: "unicode", what: "UTF-8 as code points, and simple case mapping.", lines: 216, tests: 11 },
  { name: "bignum", what: "Arbitrary-precision integers.", lines: 615, tests: 41 },
  { name: "codec", what: "Base16, base32 and base64, from RFC 4648.", lines: 349, tests: 10 },
  { name: "datetime", what: "The proleptic Gregorian calendar, and RFC 3339 timestamps.", lines: 236, tests: 13 },
  { name: "fmt", what: "Numbers to and from text.", lines: 1132, tests: 25 },
  { name: "gzip", what: "gzip (RFC 1952) and DEFLATE (RFC 1951) written in wac.", lines: 1990, tests: 83 },
  { name: "http", what: "HTTP/1.1: parsing requests and responses, and writing both.", lines: 885, tests: 26 },
  { name: "sh", what: "A shell, in wac.", lines: 4015, tests: 12 },
  { name: "stream", what: "Run a wac transform as a ReadableStream/WritableStream pair, so it consumes input as it arrives instead of taking the whole thing at once.", lines: 76, tests: 14 },
  { name: "url", what: "A WHATWG URL parser: parse, serialize, and resolve a reference against a base.", lines: 1229, tests: 27 },
  { name: "wacc", what: "Porting the wac compiler to wac, so it can eventually compile itself.", lines: 3467, tests: 11 },
  { name: "zstd", what: "Zstandard (RFC 8878) in wac.", lines: 2690, tests: 42 },
  { name: "crypto", what: "SHA-256, SHA-512/384, SHA-3, SHAKE, HMAC, HKDF, bcrypt_pbkdf, ChaCha20-Poly1305, AES-CTR, AES-GCM, X25519, Ed25519, NIST P-256 and P-384, RSA…", lines: 4942, tests: 133 },
  { name: "json", what: "JSON (RFC 8259) parsing and serialization, written in wac.", lines: 903, tests: 50 },
  { name: "wactest", what: "Assertions for tests written in wac.", lines: 237, tests: 16 },
  { name: "server", what: "An HTTP server written in wac.", lines: 333, tests: 20 },
  { name: "ssh", what: "An SSH-2 client and server, in wac, **and ssh and sshd programs built from them.", lines: 3565, tests: 45 },
  { name: "tls", what: "TLS 1.3 (RFC 8446) in wac.", lines: 3263, tests: 70 },
  { name: "box", what: "60 applets in one program, chosen by the first argument.", lines: 3091, tests: 22 },
  { name: "tor", what: "A Tor client, in wac, on top of this repo's TLS 1.3 stack.", lines: 4272, tests: 109 },
];
