// Generate `packages/raster/src/font16.wac` from the vendored unscii-16.
//
//   deno run --allow-read --allow-write packages/raster/tools/genfont.ts
//
// The same shape as `packages/unicode/tools/gentables.ts`: a generator writes a wac file of constant
// arrays and a lookup, so the run-time cost is a binary search rather than a parser. `packages/raster/tools/UNSCII.md`
// says where the input came from and why it is vendored.
//
// ## What the format is, and the two things that read it wrong
//
// Unifont `.hex` is one line per glyph, `CODEPOINT:HEXROWS`. Both halves have a trap:
//
//   - **Code points are five hex digits.** `A` is `00041:`, not `0041:`. A four-digit assumption
//     matches nothing and produces an empty font rather than an error.
//   - **Not every glyph is 8 pixels wide.** 2,997 lines carry 32 hex characters (16 rows of one
//     byte) and **243 carry 64** — 16 rows of *two* bytes, so 16 pixels wide. They are the CJK and
//     emoji code points, the ones a terminal already gives two cells. A reader that assumes one byte
//     per row draws the left half of a watch face and then treats the right half as the next row.
//
// ## How it is stored
//
// Rows are packed four to an `i32`, most significant byte first, and a glyph's rows are contiguous.
// A wide glyph's row is two bytes, so it takes two of those slots per four rows — the width is in
// the index rather than inferred, because inferring it is the mistake above.
//
// Three parallel arrays keyed by code point, sorted, binary-searched:
//
//   `GLYPH_CP`     the code point
//   `GLYPH_AT`     where its rows start in `GLYPH_ROWS`
//   `GLYPH_WIDE`   1 if it is 16 pixels wide, 0 if 8
//
// **`GLYPH_ROWS` is 13,932 `i32`s**, and that is the whole font. `packages/unicode`'s README warns
// that a module's constant arrays are all emitted when it is linked, so a program wanting one table
// carries the others — which is why the glyphs live in their own module with nothing else in it.

const HEX = new URL("./unscii-16.hex", import.meta.url).pathname;
const OUT = new URL("../src/font16.wac", import.meta.url).pathname;

/** The cell: unscii-16 is 8x16, and a wide glyph is 16x16. */
const ROWS = 16;

type Glyph = { cp: number; wide: boolean; rows: number[] };

const glyphs: Glyph[] = [];
for (const line of (await Deno.readTextFile(HEX)).split("\n")) {
  const colon = line.indexOf(":");
  if (colon < 0) continue;
  const cp = parseInt(line.slice(0, colon), 16);
  const bits = line.slice(colon + 1).trim();
  if (bits.length === 0) continue;
  // 32 characters is 16 bytes is one byte a row; 64 is two.
  const perRow = bits.length / 2 / ROWS;
  if (perRow !== 1 && perRow !== 2) {
    throw new Error(`genfont: U+${cp.toString(16)} has ${bits.length} hex chars, which is neither 8 nor 16 wide`);
  }
  const rows: number[] = [];
  for (let r = 0; r < ROWS; r++) {
    const at = r * perRow * 2;
    rows.push(parseInt(bits.slice(at, at + perRow * 2), 16));
  }
  glyphs.push({ cp, wide: perRow === 2, rows });
}
glyphs.sort((a, b) => a.cp - b.cp);

// Rows into bytes, then bytes packed four to an i32. A wide row is two bytes, high byte first, so a
// glyph's bytes are simply its rows flattened — the width says how to read them back.
const bytes: number[] = [];
const at: number[] = [];
for (const g of glyphs) {
  at.push(bytes.length);
  for (const row of g.rows) {
    if (g.wide) bytes.push((row >> 8) & 0xff, row & 0xff);
    else bytes.push(row & 0xff);
  }
}
while (bytes.length % 4 !== 0) bytes.push(0);
const packed: number[] = [];
for (let i = 0; i < bytes.length; i += 4) {
  // `| 0` so the value is a signed i32, which is what wac's `i32` is and what the literal must read
  // as: 0x80000000 unsigned would be out of range for the type.
  packed.push(((bytes[i] << 24) | (bytes[i + 1] << 16) | (bytes[i + 2] << 8) | bytes[i + 3]) | 0);
}

/**
 * How many words go in one constant array.
 *
 * V8 caps `array.new_fixed` at 10,000 elements, and this font is 13,932 words — so a single
 * `const i32[]` does not compile at all: "Requested length 13932 for array.new_fixed too large".
 * 8,192 leaves room for the font to grow without another split and stays clear of the ceiling.
 */
const CHUNK = 8192;
const chunks: number[][] = [];
for (let i = 0; i < packed.length; i += CHUNK) chunks.push(packed.slice(i, i + CHUNK));

const wide = glyphs.filter((g) => g.wide).length;
const out = `// Generated by tools/genfont.ts from the vendored unscii-16. Do not edit.
//
// ${glyphs.length} glyphs, of which ${wide} are 16 pixels wide rather than 8. The cell is 8x16, and
// \`GLYPH_WIDE\` is how a caller knows which glyphs take two cells — see \`packages/raster/tools/UNSCII.md\` for the
// licence (public domain) and \`design/system/0004\` for why this font.
//
// Rows are packed four bytes to an \`i32\`, most significant first, and a glyph's rows are contiguous
// from \`GLYPH_AT\`. A narrow glyph is one byte a row and a wide one is two, high byte first.
//
// **Nothing else lives in this module.** A module's constant arrays are all emitted when it is
// linked, so a program that wants a glyph should not also carry whatever else a font module grew —
// the same reason \`packages/unicode\` keeps \`printable.wac\` apart from \`tables.wac\`.

/** The code point of each glyph, ascending, so a lookup is a binary search. */
const i32[] GLYPH_CP = i32[](${glyphs.map((g) => g.cp).join(", ")});

/** Where each glyph's rows begin, as a byte offset into \`GLYPH_ROWS\`. */
const i32[] GLYPH_AT = i32[](${at.join(", ")});

/** 1 where the glyph is 16 pixels wide, 0 where it is 8. */
const i32[] GLYPH_WIDE = i32[](${glyphs.map((g) => (g.wide ? 1 : 0)).join(", ")});

${chunks.map((c, i) => `/** Rows ${i * CHUNK}.. — see \`byteAt\`. */\nconst i32[] GLYPH_ROWS${i} = i32[](${c.join(", ")});`).join("\n\n")}

/** How many glyphs there are, for a caller that wants to know what it has. */
export i32 glyphCount() { return ${glyphs.length}; }

/**
 * The index of \`cp\` in the tables, or -1.
 *
 * A binary search rather than a map: the code points are sorted at generation, and a 3,240-entry
 * table searched sixteen times is cheaper to build than a hash and cheaper to link than either.
 */
export i32 glyphIndex(i32 cp) {
  i32 lo = 0;
  i32 hi = GLYPH_CP.len() - 1;
  while (lo <= hi) {
    i32 mid = lo + (hi - lo) / 2;
    i32 v = GLYPH_CP[mid];
    if (v == cp) { return mid; }
    if (v < cp) { lo = mid + 1; } else { hi = mid - 1; }
  }
  return -1;
}

/** Whether the glyph at \`idx\` is 16 pixels wide. \`false\` for an index nobody has. */
export bool glyphWide(i32 idx) {
  if (idx < 0 || idx >= GLYPH_WIDE.len()) { return false; }
  return GLYPH_WIDE[idx] == 1;
}

/** How many pixels wide the glyph at \`idx\` is: 8, 16, or 0 for an index nobody has. */
export i32 glyphWidth(i32 idx) {
  if (idx < 0 || idx >= GLYPH_WIDE.len()) { return 0; }
  return GLYPH_WIDE[idx] == 1 ? 16 : 8;
}

/**
 * One row of the glyph at \`idx\`, as a bit pattern with the leftmost pixel in the high bit.
 *
 * A narrow glyph answers in bits 7..0 and a wide one in bits 15..0, so a caller shifts by
 * \`glyphWidth(idx) - 1 - column\`. Out of range answers 0, which draws nothing — a missing glyph
 * should leave a hole rather than a trap.
 */
export i32 glyphRow(i32 idx, i32 row) {
  if (idx < 0 || idx >= GLYPH_AT.len() || row < 0 || row >= 16) { return 0; }
  bool wide = GLYPH_WIDE[idx] == 1;
  i32 at = GLYPH_AT[idx] + row * (wide ? 2 : 1);
  i32 hi = byteAt(at);
  return wide ? (hi << 8) | byteAt(at + 1) : hi;
}

/**
 * One byte out of the packed rows.
 *
 * **Split across ${chunks.length} arrays because a constant one cannot hold them all.** V8 refuses
 * \`array.new_fixed\` above 10,000 elements — "Requested length ${packed.length} for array.new_fixed too
 * large" — and the whole font is ${packed.length} words. The chunk size is ${CHUNK}, so the division
 * below is by a constant and the arrays stay well inside the limit even as the font grows.
 */
i32 byteAt(i32 i) {
  i32 w = i / 4;
  i32 shift = (3 - (i % 4)) * 8;
  i32 word = ${chunks.map((_, i) =>
    i === chunks.length - 1
      ? `GLYPH_ROWS${i}[w - ${i * CHUNK}]`
      : `w < ${(i + 1) * CHUNK} ? GLYPH_ROWS${i}[w - ${i * CHUNK}] : `).join("")};
  return (word >> shift) & 0xFF;
}
`;

await Deno.writeTextFile(OUT, out);
console.log(
  `wrote ${OUT} — ${glyphs.length} glyphs (${wide} wide), ` +
    `${packed.length} i32 of rows, ${(out.length / 1024).toFixed(0)} KiB of source`,
);
